
load "io".
load "util".

-- UPDATED 6-28-21 to reflect issue #27 resolution
--------------------------------------------------TEST1--
try
    let (x,x) = (1,1).
    println x.
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.").
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------TEST2--
try
    let [x,w,y,[a,b,x]] = [1,2,3,[1,2,1]].
    println x.
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.").
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------TEST3--
try
    let (name:%string,name:%string) = ("a","a").
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.")
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------TEST4--
try
    let p1 = pattern with x.
    let p2 = pattern with x.
    let p3 = pattern with (*p1,*p2).
    let *p3 = ("a","a").
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.")
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------TEST5--
try
    let false = ((1,1) is (x,x)).
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.")
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------TEST6--
try
    function foo
        with (x,x) do
            return 1.
        orwith (x,y) do
            return 2.
        orwith x do
            return 3.
        end.

    assert( foo( (1,1) ) == 2 ).
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.")
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------TEST7--
try
    let myList = [ (1,1) , (2,2) , (3,3) ].
    let counter = 0.

    for (x,x) in myList do
        let counter = counter + 1.
    end.

    assert(counter == 0).

    for (x,y) in myList do
        let counter = counter + 1.
    end.

    assert(counter == 3).
catch Exception(kind, s) do
    if not isnone(s @index("non-linear")) do
        println("PASSED.")
    else
        println("FAILED.").
        throw Error("FAIL: unexpected error "+s).
    end.
end.
--------------------------------------------------END----